### ISSUE TITLE
Remove +/- UI controls from the map

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#126]
**Describe the the feature request**
A clear and concise description of the feature.

**Comment by ezwelty** [comment]
This page describes how to disable or edit Google Maps UI elements:
https://developers.google.com/maps/documentation/javascript/controls

The current mobile app uses the following settings:

```js
new google.maps.Map(element, {..., disableDefaultUI: true, tilt: 0})
```

And custom +/- zoom buttons that call the function:

```js
(dz) -> {
  map.setZoom(map.getZoom() + dz)
}
```

![Screenshot_20210524-162305](https://user-images.githubusercontent.com/377523/119366812-93fa2200-bc6e-11eb-8401-dc2b792ac4fc.jpg)

**Comment by ezwelty** [comment]
As fas as I can tell, the +/- (zoom) controls have been removed from the map.
