### ISSUE TITLE
Redesign navigation to be more compact

### ISSUE THREAD

**Issue by SirajChokshi** [hack4impact-uiuc/falling-fruit#134]
- Make a more compact navigation
- Scales for devices

**Comment by ezwelty** [comment]
Some suggestions to make the mobile (and desktop) design more compact.

- Reduce the height of the footer.
  - Remove the orange selection bar.
  - Use either an icon or a text label, but not both. For example, use a gear icon for Settings, a "Map" and "List" label for the two different views, and perhaps an "add location" icon to the far right? See the current mobile app screenshot below.
- Reduce the height of the search header.
  - Remove the padding above and below the search input and remove borders as needed. See the current mobile app screenshot below.
  - Add "go to/track current location" icon to the left side.
- Reduce the height of the location details header.
- Reduce height of forms.
  - Replace section headers with example text in text fields and dropdowns. See the current mobile app screenshot below.

![Screenshot_20210524-162305](https://user-images.githubusercontent.com/377523/119362979-8b9fe800-bc6a-11eb-9593-44c449dc05dd.jpg)

![Screenshot_20210524-164157](https://user-images.githubusercontent.com/377523/119364719-67450b00-bc6c-11eb-9e7f-053cabe0c772.jpg)
