### ISSUE TITLE
Add imperial/metric distance setting

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#135]
**Describe the the feature request**

- Should be localized

**Comment by ezwelty** [comment]
I would suggest adding a "Units" dropdown in the Settings:

- Metric
- Imperial

Which defaults to Metric (because, c'mon America!).

**Comment by Qrtn** [comment]
@abehara2 could you tag this issue in your PR?

**Comment by Qrtn** [comment]
Closed by #213
