### ISSUE TITLE
Rebuild type filtering with rc-tree

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#138]
https://github.com/react-component/tree

https://tree-react-component.vercel.app

## Why is rc-tree better?

* It's inherently not a dropdown select. The react-dropdown-tree-select library forced a selection box on the user. In general you shouldn't have to "fight" a lot of CSS to use this
* It's used as the base for the tree select in Ant Design, so you know it's legit
* It's pretty barebones so should be styleable
* @SirajChokshi worked with it over the summer and said it was decent
* It's very frequently updated: https://github.com/react-component/tree/releases (last update 12 hrs ago!?)

However... since we need search, you should probably look into `rc-tree-select` (https://tree-select-react-component.vercel.app) too. Is there a way to keep the dropdown open? Or should we just stick to `rc-tree` and make our own search box?

## What do you need to do?

* Upgrade/create a component in `components/filter/TreeSelect.js` that wraps `rc-tree`
  * `TreeSelect` takes the data in Falling Fruit's format and renders it in the tree
  * `TreeSelect` should also have a callback for when the selection changes
* Upgrade/create a component in `components/filter/Filter.js` that uses your TreeSelect component
  * This will actually hook up TreeSelect to the rest of the app by connecting it to Redux
  * See existing code for a base
* Improve/adapt the process of converting data from the backend into a tree
  * Read, understand, ask questions about `utils/buildTypeSchema.js`
  * This is how a flat list of types from the backend gets converted into a tree for the tree select library
  * `rc-tree` will definitely take data in a slightly different format (still a tree), so you guys will need to adapt this
  * Be actively thinking about how you could potentially rewrite this code to be better and more readable
* Implement additional features
  * See Ethan's post below
  * Ask Siraj how these additional operations should look
    * Tree itself is same designs from last semester

Not sure what this means since I wrote it a while ago:
- Use approximate count endpoint so that type filtering works at any zoom level

@ezwelty mentioned that we should actively be in-sync with him on the progress of this feature, so let's continuously seek feedback from him while we rebuild this.

**Comment by ezwelty** [comment]
Looking at my ancient draft code for a multi-type filter, here are the different operations I was considering. Things to keep in mind as we iterate.

- Text-based search
- Expand all / Collapse all
- Select all / Clear all / Select all from map
- Show / Hide unselected
- Show / Hide zero-count
- Update type counts from map
- Apply filter

**Comment by Qrtn** [comment]
https://github.com/react-component/tree

https://tree-react-component.vercel.app

## Why is rc-tree better?

* It's inherently not a dropdown select. The react-dropdown-tree-select library forced a selection box on the user. In general you shouldn't have to "fight" a lot of CSS to use this
* It's used as the base for the tree select in Ant Design, so you know it's legit
* It's pretty barebones so should be styleable
* @SirajChokshi worked with it over the summer and said it was decent
* It's very frequently updated: https://github.com/react-component/tree/releases (last update 12 hrs ago!?)

## What do you need to do?

* Upgrade/create a component in `components/filter/TreeSelect.js` that wraps `rc-tree`
  * `TreeSelect` takes the data in Falling Fruit's format and renders it in the tree
  * `TreeSelect` should also have a callback for when the selection changes
* Upgrade/create a component in `components/filter/Filter.js` that uses your TreeSelect component
  * This will actually hook up TreeSelect to the rest of the app by connecting it to Redux
  * See existing code for a base
* Improve/adapt the process of converting data from the backend into a tree
  * Read, understand, ask questions about `utils/buildTypeSchema.js`
  * This is how a flat list of types from the backend gets converted into a tree for the tree select library
  * `rc-tree` will definitely take data in a slightly different format (still a tree), so you guys will need to adapt this
  * Be actively thinking about how you could potentially rewrite this code to be better and more readable
