### ISSUE TITLE
Add setting for showing businesses on map

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#140]
## Description

Seeing businesses on the map can be distracting for foragers who are trying to focus on fruit locations.

We need a setting for whether businesses are currently shown on the map.

![image](https://user-images.githubusercontent.com/4369024/140625137-3b51d468-90f9-415a-98da-b69e4b2ac616.png)

The full design for this is in the Figma. We should already have components for labels and checkboxes.

Recommended branch name: `show-businesses-setting`

## Learning objectives

- Understanding Redux and Redux toolkit
  - What exactly are actions and reducers?
- Using a React library that wraps an existing, imperative JavaScript API
  - From the very beginning, Google has provided a vanilla JavaScript API for Google Maps.
    - https://developers.google.com/maps/documentation/javascript/overview
  - Since we're using React, we decided to use a wrapper library around the vanilla API that provides components for us to use. That way, we don't have to use the raw JS API directly.
    - https://github.com/google-map-react/google-map-react
  - However, sometimes we need to use functionality in the raw JS API that the wrapper doesn't specifically address. How do we convey to our wrapper library that we want to do something that Google provides?
- Integrating UI components with global state in Redux

## Todo

- Add a piece of state for showing businesses in the Redux store
  - Make sure it's off by default
- Add a checkbox to the settings UI to enable/disable this
- Link that state to whether the map shows businesses or not

## Useful links

- You need to do some research on the best way to pass options to google-map-react. @daniel-moon32 might be able to help with this, since he's also working on accessing the Google Maps API directly.
- google-map-react documentation: https://github.com/google-map-react/google-map-react
- original Google API documentation: https://developers.google.com/maps/documentation/javascript/overview
- **Ethan's comment below**
- Redux Toolkit quick start: https://redux.js.org/tutorials/quick-start
  - Redux core concepts: https://redux.js.org/introduction/core-concepts
  - Lots of short videos on Redux from the creator of React! https://egghead.io/courses/fundamentals-of-redux-course-from-dan-abramov-bd5cc867

**Comment by ezwelty** [comment]
Looks like this could be accomplished with a JSON style declaration.

Reference: https://developers.google.com/maps/documentation/javascript/style-reference
Show/hide example: https://developers.google.com/maps/documentation/javascript/examples/hiding-features
