### ISSUE TITLE
Add row-based hover effects to entry details

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#143]
## Learning objectives

- Objective

## Todo

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- Todo

## Useful links

- Useful link

**Comment by ezwelty** [comment]
How is this different from #141 ?

**Comment by Qrtn** [comment]
Whoops, thanks Ethan. Duplicate of #141.
