### ISSUE TITLE
Selectively clear and add locations

### ISSUE THREAD

**Issue by ezwelty** [hack4impact-uiuc/falling-fruit#168]
The current behavior is to drop all locations from the map and add new locations from the API on each map pan or zoom. This slows down the map and creates a hectic visual experience for the user in areas where the location count is above the limit.

I would suggest using the strategy used by the current website and mobile app: drop only the locations that are out of bounds and skip redrawing locations returned by the API that are already on the map.

**Comment by Qrtn** [comment]
Thank you for bringing this up! I just compared with fallingfruit.org and noticed what you mean. The existing implementation does not drop existing locations if they already appear on the map/have been fetched previously.

Implementing this should improve the visual experience a lot.
