### ISSUE TITLE
Main Map Display

### ISSUE THREAD

**Issue by rxun** [hack4impact-uiuc/falling-fruit#21]
## Description
The main map view of the app is where users will first land and is likely where they will spend most of their time. This map view displays all of the locations in a given area that are available for foraging.

## Objectives
- [X] Users should be able to view location pins on the map, clustered by density, on a Google Map so they can see a general overview of nearby pins. 
- [x] Users should also be able to scroll and zoom to move on the map so they can browse local locations.

## Todo / Backlog
-

**Comment by Qrtn** [comment]
Resolved by #8, #25.
