### ISSUE TITLE
Map Location Filter

### ISSUE THREAD

**Issue by rxun** [hack4impact-uiuc/falling-fruit#23]
## Description
Falling Fruit comes with a huge number of location types. The filters should help the user narrow down what sorts of locations they'd like to explore.

## Objectives
- [ ] Users should be able to select which edible types they want to include on the map display so they can narrow down what sorts of locations they'd like to explore.
- [ ] Users should be able to select and unselect special filters (tree inventories, invasive species).

## Todo / Backlog
-

**Comment by Qrtn** [comment]
Closed by #42 (issue in #40).
