### ISSUE TITLE
Clean up user sign up form

### ISSUE THREAD

**Issue by ezwelty** [hack4impact-uiuc/falling-fruit#249]
The user sign up form (https://falling-fruit.vercel.app/signup) needs to be reorganized to match the API.

- [x] Remove the two checkboxes. Editing anonymously is no longer an option while logged in, and we need to have the option to email users if the situation is important enough to warrant it.
- [x] Make `name` optional and move to above `bio`
- [x] Make `password_confirmation` invalid if empty and `password` is not empty
- [x] Require `password` to be 6 characters or longer (to match current mobile app)
- [x] Add reCaptcha

Currently, the API will return an error if the email is already taken. This means we need to show a (translated) message that this happened. However, it may be better to always send the email, but vary the content of the email based on whether the email was already taken or not – in which case, if the form is valid, it should always succeed.

**Comment by Qrtn** [comment]
@ezwelty For certain form errors that can only be detected on the server-side (duplicate email), you may want to return a short string identifying the error in a separate field from `error`, so that we can check for it in the client and display an appropriate translated message.
