### ISSUE TITLE
Unrecognized/Invalid Bounds during Map Roll Around

### ISSUE THREAD

**Issue by vasuchal** [hack4impact-uiuc/falling-fruit#28]
**Describe the bug**
The Google Map React Library increments longitudinal bounds by 360 degrees for every revolution ("roll around") by the user from the left or the right. This causes the API to return empty data instead of clusters and locations during roll arounds of 360 degrees or more as the API does not recognize the scaled longitudes. Roll arounds to the left decrement by 360 each time and increment by 360 each time for roll arounds to the right.

**To Reproduce**

1. Go to http://localhost:3000/login
2. Click on the map and rotate to the right by 360 degrees until you are back at the location you started on
3. Clusters will not appear on this view of the map.
4. Go back 360 degrees to the left to reverse your actions and clusters will once again appear. 
5. Using chrome developer tools, the increment of longitude through these roll arounds can be seen as well.

**Screenshots**
First screenshot: map with longitudinal bounds that are in scope of API
Second screenshot: map after around to right with longitude bound incremented by 360
Third screenshot: map after roll around to left with longitude bound decremented by 360
<img width="1792" alt="Screen Shot 2021-03-01 at 7 59 51 PM" src="https://user-images.githubusercontent.com/40867028/109585345-fce75900-7ac8-11eb-9083-cbac598de28a.png">
<img width="1792" alt="Screen Shot 2021-03-01 at 8 00 42 PM" src="https://user-images.githubusercontent.com/40867028/109585353-01ac0d00-7ac9-11eb-851d-312d87fc55c3.png">
<img width="1792" alt="Screen Shot 2021-03-01 at 8 01 37 PM" src="https://user-images.githubusercontent.com/40867028/109585363-040e6700-7ac9-11eb-884b-a4cad39a8f00.png">

**Comment by Qrtn** [comment]
Thanks @vasuchal for catching and reporting this!
