### ISSUE TITLE
Highlight selected location in desktop view

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#47]
**Describe the the feature request**
A clear and concise description of the feature.

**Comment by ezwelty** [comment]
The icon used to highlight a location on the map could be the same size and shape as the regular icon, but a different color, to avoid hiding locations behind it. However, if the regular icon were made smaller, or if in crowded areas the color change isn't enough to catch the eye, then I can see the value of using a pin-style icon instead.

**Comment by Qrtn** [comment]
Closed by #122.

**Comment by Qrtn** [comment]
@ezwelty, I'll discuss the icon used for highlighting a location with @SirajChokshi!
