### ISSUE TITLE
Reports 

### ISSUE THREAD

**Issue by rxun** [hack4impact-uiuc/falling-fruit#53]
## Description
Reports are used to flag locations that may not be valid. An admin can then review and edit/delete the given location. In the desktop version, this is a small popup, so this can be more minimal / less invasive.

Please check Figmas for most recently updated user flows + designs (and the [feature specification doc](https://docs.google.com/document/d/1IgJHD5zaEB_81YF-zPeaPRSLb5_aWWbMMdQs6dd9XtQ/edit#heading=h.sq4fw9julrxt) for any other information). 

## Objectives
- [ ] *P1*: Users should be able to flag locations that are not valid by submitting a form (check valid problem types in the feature spec doc). 
- [ ] *P2*: Admins should be able to review and edit/delete the given location.

## Todo / Backlog
- Outcome of flagged activity being documented?

**Comment by ezwelty** [comment]
Report resolution is logged as one of the following:

- Made no changes
- Edited the location
- Deleted the location
- Deleted the photo
- Deleted the review
- Hid the location (replacing "Deleted the location")

In practice, we display a table of unresolved reports by date, user (or email if reported when not logged in), location id, and report. Admin can write their response into the text box, select from a dropdown of the options above, and optionally select to email their response to the user by checking an "Email" checkbox.
