### ISSUE TITLE
Form progress bar

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#58]
## Description

Create progress bar showing the steps in the form:

![image](https://user-images.githubusercontent.com/4369024/113340444-87ea8780-92f1-11eb-939e-094fd7511224.png)

`ui/ProgressBar.js`

Branch name: `form-progress`

## Todo

- Create the component in ui
- Break down the whole progress bar component into multiple components for easier styling and separation of concerns
- Decide on what makes sense to take as props for this component
  - currentStep
  - onChange
  - labels: an array of N labels. This also determines the number of steps (N)
- Styling
  - Track, circles, labels under the track
- Integrate props
- Test

## Useful links

- https://medium.com/@beyondborders/building-a-responsive-and-dynamic-progress-bar-5d52c1f66c24
- Siraj

**Comment by yousefa00** [comment]
Useful links -> Siraj 😂

**Comment by Qrtn** [comment]
It's true!!
