### ISSUE TITLE
Form type selection

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#59]
## Description

Refactor the existing tree select component to handle displaying the currently selected types, and so that it's not tied to context (tied to props). Then, there will be two instances of the tree select: one in filter, one in the new location form. Take a prop that shows whether or not to display tags.

![image](https://user-images.githubusercontent.com/4369024/113342280-ec0e4b00-92f3-11eb-9d62-7ecc12e6fc35.png)

Branch name: `form-type-selection`

## Todo

- Refactor out existing component
- Style tags
- Take a prop that shows whether or not to display tags
- When the component is used for selection in the form, the types tree will be a true dropdown/popover over existing content. This will require "unstyling" some of the things you did to make it lie directly on the page (height: 100%, etc.)
- Take a prop for whether it's a popover or not ^^
- Some additional logic changes: you might want to make parent components unselectable, because it shouldn't make sense for the user to easily select a ton of types. They should select one in particular. Clarify with Siraj

## Useful links

- Dow Jones documentation
- Existing Falling Fruit implementation of selecting types in a new location

**Comment by laurenho025** [comment]
For now, @SirajChokshi and @rxun agreed that we should allow users to select whatever they want (including parent nodes). This is something that we should clarify with Ethan.
