### ISSUE TITLE
Form caption input

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#64]
## Description

Wrap ListEntry, use CircleIcon, Input, IconButton

![image](https://user-images.githubusercontent.com/4369024/113354870-77dca300-9305-11eb-807c-1a6056d90b97.png)

Component: `ui/CaptionInput.js`
Branch name: `form-caption-input`

## Todo

- In your final exposed component, have props: value (for the Input), onChange (for the Input), onDelete (for the IconButton), image (for the CircleIcon)

## Useful links

- Useful link

**Comment by Archna-1** [comment]
Forgot to link this to the PR, but just merged in.
