### ISSUE TITLE
Fix type filtering infinite scroll

### ISSUE THREAD

**Issue by laurenho025** [hack4impact-uiuc/falling-fruit#65]
**Describe the bug**
The [react-dropdown-tree-select](https://github.com/dowjones/react-dropdown-tree-select) library that we use for type filtering uses an infinite scroll component internally. This is supposed to limit the tree to 100 items initially, and should load more as you scroll to the bottom. Currently, all data is fetched, however additional types are not loaded into the tree selector if you scroll to the bottom. 

**To Reproduce**

1. Press the filter icon in the top right to bring up the tree selector
2. Console log the data that is passed into the tree to verify that 100+ type filters are fetched from the server
3. Scroll down to the bottom of the tree selector
4. See error (additional types not loaded into the tree as you scroll to the bottom)

**Expected behavior**
Additional type options should be loaded into the tree selector as you scroll towards the bottom.

**Comment by Qrtn** [comment]
@laurenho025 I think you can tag this issue in your type filter rebuild PR, should probably be resolved.
