### ISSUE TITLE
Fix the scary label overlap issue 

### ISSUE THREAD

**Issue by code-arman** [hack4impact-uiuc/falling-fruit#96]
**Describe the the feature request**
In areas with lots of location entries, many of the labels overlap resulting in...scariness (see below) 😨 

- Use the information we know about what else is in the current view state to determine when it is appropriate to show the zoom level
<img width="939" alt="Screen Shot 2021-04-16 at 11 47 41 AM" src="https://user-images.githubusercontent.com/46976119/115650359-adfeb880-a2ee-11eb-8edd-f83274dda209.png">

**Comment by ezwelty** [comment]
Two things that we did on the current website to make it look less scary (but still just as messy) was to place the text labels beneath the placemarks, use a thin white stroke around the text, and make the text opaque.

![labels](https://user-images.githubusercontent.com/377523/115910238-d3dca800-a429-11eb-8ab1-9cf897913cd9.png)
